# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_act.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'data_act.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61ta_act.proto\" \n\x10StringMessageACT\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2M\n\x17\x42idirectionalServiceACT\x12\x32\n\x04\x43hat\x12\x11.StringMessageACT\x1a\x11.StringMessageACT\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_act_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGMESSAGEACT']._serialized_start=18
  _globals['_STRINGMESSAGEACT']._serialized_end=50
  _globals['_BIDIRECTIONALSERVICEACT']._serialized_start=52
  _globals['_BIDIRECTIONALSERVICEACT']._serialized_end=129
# @@protoc_insertion_point(module_scope)
